name: Node.js Testing

on:
    push:
        branches: ["main", "issue-21-b"]
    pull_request:
        branches: ["main", "issue-21-b"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [24.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: yarn install
            - run: node --test src/test/*.test.js
